### ISSUE TITLE
Infinite redirect upon login

### ISSUE THREAD

**Issue by ChunYin** [YPlan/nexus#52]
If you do not have staff access but you have signed in, there's a line (https://github.com/Yplan/nexus/blob/master/nexus/sites.py#L209) that does a redirect to the index:nexus, which is the page you are currently at, so it does an infinite redirect.

My url for nexus looks like this:
`url(r'^nexus/', include(nexus.site.urls)),`

The nexus module has checks for staff access in a function a couple levels above the aforementioned function (https://github.com/YPlan/nexus/blob/master/nexus/sites.py#L81), and it looks like this line is bypassing that.

**Comment by adamchainz** [comment]
Ah thank you very much. I wasn't sure after I removed the custom login in #12 if it had had any side effects, turns out it has! Will fix it later today.

**Comment by ChunYin** [comment]
Thank you! Much appreciated. :) (Also, thank you Yplan for maintaining Gargoyle/Nexus/ModelDict.)

**Comment by adamchainz** [comment]
Please try version 1.3.0 as just published on PyPI, the fix from #53 is included in that. Thanks!
