### ISSUE TITLE
Bottom banner on top of content

### ISSUE THREAD

**Issue by gjcarneiro** [YPlan/nexus#65]
The bottom banner showing Nexus version etc. is overlaid on top of the content, and hides some of my gargoyle switches.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/2197096/15509908/1f3abf1a-21cd-11e6-879c-0707935950c8.png)

**Comment by gjcarneiro** [comment]
Just commenting out the `position:aboslute` in the nexus css is enough for me.

```
#footer {
    background-color: #ffffff;
    border-top: 1px solid #d5d9db;
    padding: 20px 0;
    //position: absolute;
...
```

**Comment by adamchainz** [comment]
This was already fixed in #56 / 86e3ce58f0459607cbda4111b53d15fa42979af3 but hasn't been released - sorry about that, will release now.

**Comment by adamchainz** [comment]
1.4.0 just released [on PyPI](https://pypi.python.org/pypi/nexus-yplan), enjoy.

**Comment by gjcarneiro** [comment]
Cheers!
