### ISSUE TITLE
Javascript getCookie(CSRF-cookie) does not work with CSRF_COOKIE_HTTPONLY

### ISSUE THREAD

**Issue by Duologic** [YPlan/nexus#90]
Hi all

I would like to address a small issue as we are trying to switch to the YPlan's maintained version of `nexus` and `gargoyle` instead of using our own fork.

To protect our website from hijacking the CSRF cookie, we currently set [CSRF_COOKIE_HTTPONLY](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY) in Django. As a side effect on this, the Ajax requests for Gargoyle do not work.

I've noticed that Nexus tries to [get the cookie with Javascript](https://github.com/YPlan/nexus/blob/master/nexus/media/js/nexus.js#L38), this is exactly what CSRF_COOKIE_HTTPONLY is trying to prevent.

In our own fork, we have worked around this issue by including the CSRF token [as a template tag](https://github.com/vikingco/gargoyle/commit/05f74386c31645a04b81544db82e4d19193098ed) instead of fetching it with Javascript from the browser.

What would be the recommended way to implement this into the YPlan's fork? I'd be happy to create a pull request for this so we can maintain a certain level of security (as [recommended by OWASP](https://www.owasp.org/index.php/HttpOnly)).

Thanks!

**Comment by adamchainz** [comment]
Create a PR! But your current implementation is on Gargoyle, and includes inline JS which I spent some time removing to work with sites using CSP. You should instead make it a data attribute in the template: https://github.com/YPlan/nexus/blob/master/nexus/templates/nexus/base.html#L20 and then pull it out with jQuery, like we do with the cookie name currently: https://github.com/YPlan/nexus/blob/master/nexus/media/js/nexus.js#L37

**Comment by graingert** [comment]
There's not really much point in setting CSRF_COOKIE_HTTPONLY if you put it straight into the page where JavaScript can get it anyway.

**Comment by graingert** [comment]
@Duologic if you want to prevent JavaScript hijacking of the cookie I'd recommend deploying https://django-csp.readthedocs.io/en/latest/ and white-listing the JavaScript that you want to run in your pages instead.

**Comment by graingert** [comment]
@adamchainz not that nexus shouldn't support this configuration.

**Comment by adamchainz** [comment]
> There's not really much point in setting CSRF_COOKIE_HTTPONLY if you put it straight into the page where JavaScript can get it anyway.

At least with Neuxs it will only be on admin-only pages

**Comment by Duologic** [comment]
`django-csp` is definitely worth looking into in the long term, it would add an extra layer to the security but unfortunately add an extra layer of complexity too.

I think the risk for inserting the CSRF cookie into the nexus interface is rather low as these pages are usually only accessed by Admin's, like @adamchainz mentions. On our end, we even prevent access to these pages on the public internet.

Our hack was really dirty, so we'll make a pull request with the proposed solution. 

Thanks for all the quick responses!

**Comment by Duologic** [comment]
I've created a pull request, anyone care to review this? :bowing_man:
